---

- name: Install Conky
  hosts: localhost

  tasks:
  - name: Install Conky
    become: yes
    ansible.builtin.apt:
      pkg:
      - conky

  - name: Create autostart directory
    ansible.builtin.file:
      path: /home/jeremy/.config/autostart
      state: directory
      mode: 0700

  - name: Symlink conky to autostart
    ansible.builtin.file:
      src: /usr/share/applications/conky.desktop
      dest: /home/jeremy/.config/autostart/conky.desktop
      state: link

  - name: Copying conkyrc
    ansible.builtin.copy:
      src: files/conkyrc
      dest: /home/jeremy/.conkyrc
      owner: jeremy
      group: jeremy
      mode: 0600