---

- name: Install dependencies
  hosts: localhost

  tasks:
  - name: Enabling armhf packages
    become: yes
    ansible.builtin.command:
      cmd: "dpkg --add-architecture armhf"

  - name: Installing dependencies
    become: yes
    ansible.builtin.apt:
      pkg:
      - build-essential
      - git
      - cmake
      - gfortran
      - fftw3-dev
      - qtbase5-dev
      - qttools5-dev
      - libqt5serialport5-dev
      - qtmultimedia5-dev
      - libqt5multimedia5-plugins
      - libqt5sql5-sqlite
      - autoconf
      - automake
      - libtool
      - texinfo
      - libusb-1.0-0-dev
      - libudev-dev
      - libboost-all-dev
      - asciidoctor
      - libfltk1.3
      - libfltk1.3-dev
      - libsamplerate0
      - libsamplerate0-dev
      - libsndfile1
      - libsndfile1-dev
      - portaudio19-dev
      - libpulse-dev
      - libhamlib-dev
      - libudev-dev
      - fuse

  - name: installing armhf dependencies
    become: yes
    ansible.builtin.apt:
      pkg:
      - libasound2:armhf
      - zlib1g-dev:armhf
      - libglib2.0-0:armhf
      - libnss3:armhf
      - libatk1.0-0:armhf
      - libatk-bridge2.0-0:armhf
      - libx11-xcb1:armhf
      - libgdk-pixbuf-2.0-0:armhf
      - libgtk-3-0:armhf
      - libdrm2:armhf
      - libgbm1:armhf
      - fuse:armhf

  - name: creating fuse group
    become: yes
    ansible.builtin.group:
      name: fuse
      state: present

  - name: adding user to fuse group
    become: yes
    ansible.builtin.user:
      name: jeremy
      groups: fuse
      append: yes
